name: Test
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Determine Python version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup virtualenv
        run: |
          python3 -m venv ./.venv
          source .venv/bin/activate

      - name: Install dependencies
        run: pip install -Ur ./requirements.txt

      - name: Black
        run: black --check .

      - name: isort
        run: isort --check .

      - name: flake8
        run: flake8 .

      - name: Tests
        run: pytest
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
